name: build and test

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: ./build.sh
    - name: Run conversion proxy unit tests
      run: |
        - cd conversion/proxy
        - cargo test
    - name: Run integration tests
      run: ./test.sh
