name: build and test

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm32-unknown-unknown target
      run: rustup target add wasm32-unknown-unknown
    - name: Build and run conversion proxy unit tests
      working-directory: ./conversion_proxy
      run: cargo test
    - name: Build and run fungible conversion proxy unit tests
      working-directory: ./fungible_conversion_proxy
      run: cargo test
    - name: Build and run mocks unit tests
      working-directory: ./mocks
      run: cargo test
    - name: Run integration tests
      run: ./test.sh
