name: main

on:
  push:
    branches:
      - "main" 
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Rust downgrade
      run: rustup default 1.67.0
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install wasm32-unknown-unknown target
      run: rustup target add wasm32-unknown-unknown
    - name: Build contracts
      run: ./build.sh
    - name: Build mocks
      run: ./mocks/build.sh
    - name: Unit and Integration Tests
      run: cargo test --all

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cargo format check
      run: cargo fmt -- --check
    - name: Cargo clippy
      run: cargo clippy -- -D warnings
